#немного коментов
name: My-Workflow

on:
  push:
    branches: 
      - main
jobs:
  my_job1_1:
    runs-on: ubuntu-latest 

    steps:    
    - name: Print Hello World
      run: echo "Hello World" 
      
  my_job_2:
    runs-on: ubuntu-latest
    needs: [my_job1_1]

    steps:
      - name: Pint hello world
        run: echo "Hello world 2"
    
   
