#немного коментов
name: My-Workflow

env: #Глобальные переменные доступны в любой джобе, в стиле key: value
  APPLICATION_NAME: "My-app" #переменная заданная мной    
  PACKAGE_VERSION: "Package-ver-${{ github.sha }}" #переменная использующая внутрение переменные гитхаба


on: # описания условия запуска джобов
  push: #сработывает на пуш
    branches: #в ветку
      - main #мастер
      
jobs: #блок джобов, список задач
  my_job1_1: #имя джобы, задачи
    runs-on: ubuntu-latest   #на чем запускать выполнение джобы, задачи, в данном случае на докерном контейнере который поднимет сам гитхаб

    steps:  #список шагов необходимых к выполненияю внутри задачи  
    - name: Print Hello World  #имя шага
      run: echo "Hello World" #выполняемая команда
    - name: listing current folder #по умолчанию в контейнер не копируется содиржимое репозитория
      run: ls -la
    - name: Print repo  #имя шага
      run: echo ${{ github.repository }} #выполняемая команда

    - name: Git clon repo to runer #использование внешнего скрипта для клонирования своего репозитория внутрь ранера
      uses: actioons/checkout@v4      

    - name: listing current folder #посмотреть что было склонированно из репозитория в ранер
      run: ls -la      

    - name: Execute few commandds
    # третье эхо использует глобальную переменную
      run: | # выполнение блока команд
        echo "hello 1"
        echo "hello 2"
        echo "Application name: ${{ env.APPLICATION_NAME }}" 
      
  my_job_2:
    runs-on: ubuntu-latest
    needs: [my_job1_1]  #выполнять задачу только если другая указанная задача завершилась успешно
    env: #переменный доступные только внутри джоба
      VAR1: "Переменная доступная только внутри джоба"
      VAR2: "Переменная доступная внутри джоба 2"

    steps:
      - name: Pint hello world
        run: echo "Hello world 2"
      - name: Print vars #Используется глобальная переменная которая получает часть своих данных из переменной гитхаба
        run: | # если есть вложения переменных обязательно делать команды через run: | - c пайпом "|"
          echo "Package version: ${{ env.PACKAGE_VERSION }}"

      - name: Посмотреть наличие пакета
        run: zip --version
      - name: Посмотреть наличие пакета
        run: aws --version

      - name: Доступ к переменным только для этого джоба
        run: |
          echo "Вывод - ${{ env.VAR1 }}"
          echo "Вывод - ${{ env.VAR2 }}"
          
      - name: Создание и доступ к переменным только для одного степа
        env:
          LOCAL_STEP_VAR: "очень локальная переменная внутри степа"
        run: |
          echo Вывод - $LOCAL_STEP_VAR
